version: "3.8"

services:
  # Database service (SQLite for development, PostgreSQL for production)
  db:
    image: postgres:15
    container_name: hacka-fi-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-hacka_fi}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
    ports:
      - "${DATABASE_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./apps/api/prisma/migrations:/docker-entrypoint-initdb.d
    networks:
      - hacka-fi-network
    profiles:
      - production

  # NestJS Backend API
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    container_name: hacka-fi-api
    env_file:
      - .env  # Root environment variables
    environment:
      # Override root variables with container-specific values
      - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?schema=public
      - DATABASE_PROVIDER=postgresql
      - PORT=3001
      - CHAIN_ID=${KAIA_CHAIN_ID:-1001}
    ports:
      - "${API_PORT:-3001}:3001"
    volumes:
      - ./apps/api:/app
      - /app/node_modules
      - ./packages:/packages
    depends_on:
      - db
    networks:
      - hacka-fi-network
    profiles:
      - development
      - production

  # Next.js Frontend
  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    container_name: hacka-fi-web
    env_file:
      - .env  # Root environment variables
    environment:
      # Override root variables with container-specific values
      - NEXT_PUBLIC_API_URL=http://api:3001
      - NEXT_PUBLIC_KAIA_CHAIN_ID=${KAIA_CHAIN_ID:-1001}
      - NEXT_PUBLIC_HACKATHON_REGISTRY_ADDRESS=${HACKATHON_REGISTRY_ADDRESS}
      - NEXT_PUBLIC_PRIZE_POOL_ADDRESS=${PRIZE_POOL_ADDRESS}
    ports:
      - "${WEB_PORT:-3000}:3000"
    volumes:
      - ./apps/web:/app
      - /app/node_modules
      - /app/.next
      - ./packages:/packages
    depends_on:
      - api
    networks:
      - hacka-fi-network
    profiles:
      - development
      - production

  # Redis for caching (optional)
  redis:
    image: redis:7-alpine
    container_name: hacka-fi-redis
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis_data:/data
    networks:
      - hacka-fi-network
    profiles:
      - production

  # Nginx reverse proxy (production only)
  nginx:
    image: nginx:alpine
    container_name: hacka-fi-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/ssl:ro  # Mount SSL certificates directory
    depends_on:
      - api
      - web
    networks:
      - hacka-fi-network
    profiles:
      - production
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:

networks:
  hacka-fi-network:
    driver: bridge
