[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.20"
optimizer = true
optimizer_runs = 200
via_ir = false
gas_reports = [
    "HackathonRegistry", 
    "PrizePool"
]

# Kaia Network Configuration
[rpc_endpoints]
kaia_testnet = "https://rpc.ankr.com/kaia_testnet"
kaia_mainnet = "https://rpc.ankr.com/kaia"

# Chain Configuration  
[etherscan]
kaia_testnet = { key = "${SCAN_API_KEY}", url = "https://kairos-oapi.kaiascan.io/api" }
kaia_mainnet = { key = "${SCAN_API_KEY}", url = "https://mainnet-oapi.kaiascan.io/api" }

# Test Configuration
[fmt]
line_length = 100
tab_width = 4
bracket_spacing = true

